/* To avoid CSS expressions while still supporting IE 7 and IE 6, use this script */
/* The script tag referencing this file must be placed before the ending body tag. */

/* Use conditional comments in order to target IE 7 and older:
	<!--[if lt IE 8]><!-->
	<script src="ie7/ie7.js"></script>
	<!--<![endif]-->
*/

(function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'stvfont\'">' + entity + '</span>' + html;
	}
	var icons = {
		'stv-sim1': '&#xe94f;',
		'stv-sim2': '&#xe982;',
		'stv-sim3': '&#xe983;',
		'stv-sim4': '&#xe98e;',
		'stv-sim5': '&#xe98f;',
		'stv-sim6': '&#xe991;',
		'stv-sim7': '&#xe992;',
		'stv-sim8': '&#xe99b;',
		'stv-sim9': '&#xe9a8;',
		'stv-sim10': '&#xe9bf;',
		'stv-sim11': '&#xe9cb;',
		'stv-sim12': '&#xe9d7;',
		'stv-sim13': '&#xe9d8;',
		'stv-sim14': '&#xe9e2;',
		'stv-sim15': '&#xe9e3;',
		'stv-sim16': '&#xe9eb;',
		'stv-sim17': '&#xe9ec;',
		'stv-sim18': '&#xe9ee;',
		'stv-sim19': '&#xe9ef;',
		'stv-sim20': '&#xe9f0;',
		'stv-sim21': '&#xe9f1;',
		'stv-sim22': '&#xe9fa;',
		'stv-sim23': '&#xe9fb;',
		'stv-sim24': '&#xe9fc;',
		'stv-search-bg': '&#xe929;',
		'stv-home': '&#xe900;',
		'stv-home2': '&#xe901;',
		'stv-home3': '&#xe902;',
		'stv-podcast': '&#xe903;',
		'stv-price-tag': '&#xe92a;',
		'stv-price-tags': '&#xe92b;',
		'stv-cart': '&#xe904;',
		'stv-credit-card': '&#xe92c;',
		'stv-phone': '&#xe905;',
		'stv-phone-hang-up': '&#xe906;',
		'stv-envelop': '&#xe9fd;',
		'stv-printer': '&#xe907;',
		'stv-display': '&#xe908;',
		'stv-laptop': '&#xe909;',
		'stv-mobile': '&#xe90a;',
		'stv-mobile2': '&#xe90b;',
		'stv-tablet': '&#xe90c;',
		'stv-tv': '&#xe90d;',
		'stv-undo': '&#xe90e;',
		'stv-redo': '&#xe90f;',
		'stv-undo2': '&#xe910;',
		'stv-redo2': '&#xe9fe;',
		'stv-forward': '&#xe9ff;',
		'stv-reply': '&#xea00;',
		'stv-user': '&#xe911;',
		'stv-users': '&#xea01;',
		'stv-user-plus': '&#xea02;',
		'stv-user-check': '&#xe92d;',
		'stv-user-tie': '&#xea03;',
		'stv-hour-glass': '&#xe92e;',
		'stv-spinner': '&#xe92f;',
		'stv-spinner3': '&#xe930;',
		'stv-spinner6': '&#xe912;',
		'stv-spinner7': '&#xea04;',
		'stv-spinner9': '&#xe931;',
		'stv-spinner10': '&#xea05;',
		'stv-spinner11': '&#xea06;',
		'stv-search': '&#xe932;',
		'stv-zoom-in': '&#xe913;',
		'stv-zoom-out': '&#xe914;',
		'stv-lock': '&#xe933;',
		'stv-unlocked': '&#xe934;',
		'stv-trophy': '&#xea07;',
		'stv-gift': '&#xea08;',
		'stv-rocket': '&#xea09;',
		'stv-bin': '&#xea0a;',
		'stv-airplane': '&#xea0b;',
		'stv-truck': '&#xea0c;',
		'stv-accessibility': '&#xe935;',
		'stv-target': '&#xe936;',
		'stv-clipboard': '&#xea0d;',
		'stv-menu': '&#xe915;',
		'stv-menu2': '&#xe937;',
		'stv-menu3': '&#xe938;',
		'stv-menu4': '&#xe939;',
		'stv-download3': '&#xea0e;',
		'stv-upload3': '&#xea0f;',
		'stv-earth': '&#xea10;',
		'stv-flag': '&#xe922;',
		'stv-eye': '&#xea11;',
		'stv-bookmark': '&#xe923;',
		'stv-bookmarks': '&#xe924;',
		'stv-star-empty': '&#xea12;',
		'stv-star-half': '&#xea13;',
		'stv-star-full': '&#xe93a;',
		'stv-heart': '&#xea14;',
		'stv-happy': '&#xea15;',
		'stv-sad': '&#xea16;',
		'stv-wink': '&#xea17;',
		'stv-grin': '&#xea18;',
		'stv-point-right': '&#xea19;',
		'stv-point-left': '&#xea1a;',
		'stv-plus': '&#xe916;',
		'stv-minus': '&#xe917;',
		'stv-cancel-circle': '&#xea1b;',
		'stv-blocked': '&#xea1c;',
		'stv-cross': '&#xe918;',
		'stv-checkmark': '&#xe919;',
		'stv-checkmark2': '&#xe91a;',
		'stv-loop': '&#xea1d;',
		'stv-loop2': '&#xea1e;',
		'stv-arrow-up-left': '&#xea1f;',
		'stv-arrow-up': '&#xe91b;',
		'stv-arrow-up-right': '&#xea20;',
		'stv-arrow-right': '&#xe91c;',
		'stv-arrow-down-right': '&#xea21;',
		'stv-arrow-down': '&#xe91d;',
		'stv-arrow-down-left': '&#xea22;',
		'stv-arrow-left': '&#xea23;',
		'stv-arrow-up2': '&#xea24;',
		'stv-arrow-right2': '&#xea25;',
		'stv-arrow-down2': '&#xea26;',
		'stv-arrow-left2': '&#xea27;',
		'stv-circle-up': '&#xe91e;',
		'stv-circle-right': '&#xe91f;',
		'stv-circle-down': '&#xe920;',
		'stv-circle-left': '&#xe921;',
		'stv-checkbox-checked': '&#xe925;',
		'stv-checkbox-unchecked': '&#xe926;',
		'stv-paragraph-right': '&#xe93b;',
		'stv-paragraph-justify': '&#xe93c;',
		'stv-indent-increase': '&#xe93d;',
		'stv-indent-decrease': '&#xe93e;',
		'stv-mail': '&#xe93f;',
		'stv-mail2': '&#xe940;',
		'stv-mail3': '&#xe941;',
		'stv-mail4': '&#xe942;',
		'stv-google': '&#xe943;',
		'stv-google2': '&#xe944;',
		'stv-google3': '&#xe945;',
		'stv-google-plus': '&#xe946;',
		'stv-google-plus2': '&#xe947;',
		'stv-google-plus3': '&#xe948;',
		'stv-google-drive': '&#xea28;',
		'stv-facebook': '&#xe949;',
		'stv-facebook2': '&#xe94a;',
		'stv-whatsapp': '&#xea29;',
		'stv-twitter': '&#xea2a;',
		'stv-rss': '&#xe94b;',
		'stv-rss2': '&#xe94c;',
		'stv-youtube': '&#xe94d;',
		'stv-youtube2': '&#xe94e;',
		'stv-flickr4': '&#xea2b;',
		'stv-dribbble': '&#xea2c;',
		'stv-tumblr': '&#xea2d;',
		'stv-tumblr2': '&#xea2e;',
		'stv-appleinc': '&#xea2f;',
		'stv-android': '&#xea30;',
		'stv-windows': '&#xe927;',
		'stv-windows8': '&#xe928;',
		'stv-skype': '&#xea31;',
		'stv-hackernews': '&#xea32;',
		'stv-chrome': '&#xea33;',
		'stv-IE': '&#xea34;',
		'0': 0
		},
		els = document.getElementsByTagName('*'),
		i, c, el;
	for (i = 0; ; i += 1) {
		el = els[i];
		if(!el) {
			break;
		}
		c = el.className;
		c = c.match(/stv-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
}());
